export class BeforeUnloadEvent {}
export class CompositionEvent {}
export class ErrorEvent {}
export class FocusEvent {}
export class HTMLAllCollection {}
export class HTMLAnchorElement {}
export class HTMLAreaElement {}
export class HTMLAudioElement {}
export class HTMLBRElement {}
export class HTMLBaseElement {}
export class HTMLBodyElement {}
export class HTMLButtonElement {}
export class HTMLCanvasElement {}
export class HTMLDListElement {}
export class HTMLDataElement {}
export class HTMLDataListElement {}
export class HTMLDetailsElement {}
export class HTMLDialogElement {}
export class HTMLDirectoryElement {}
export class HTMLDivElement {}
export class HTMLDocument {}
export class HTMLElement {}
export class HTMLEmbedElement {}
export class HTMLFieldSetElement {}
export class HTMLFontElement {}
export class HTMLFormControlsCollection {}
export class HTMLFormElement {}
export class HTMLFrameElement {}
export class HTMLFrameSetElement {}
export class HTMLHRElement {}
export class HTMLHeadElement {}
export class HTMLHeadingElement {}
export class HTMLHtmlElement {}
export class HTMLIFrameElement {}
export class HTMLImageElement {}
export class HTMLInputElement {}
export class HTMLLIElement {}
export class HTMLLabelElement {}
export class HTMLLegendElement {}
export class HTMLLinkElement {}
export class HTMLMapElement {}
export class HTMLMarqueeElement {}
export class HTMLMediaElement {}
export class HTMLMenuElement {}
export class HTMLMetaElement {}
export class HTMLMeterElement {}
export class HTMLModElement {}
export class HTMLOListElement {}
export class HTMLObjectElement {}
export class HTMLOptGroupElement {}
export class HTMLOptionElement {}
export class HTMLOptionsCollection {}
export class HTMLOutputElement {}
export class HTMLParagraphElement {}
export class HTMLParamElement {}
export class HTMLPictureElement {}
export class HTMLPreElement {}
export class HTMLProgressElement {}
export class HTMLQuoteElement {}
export class HTMLScriptElement {}
export class HTMLSelectElement {}
export class HTMLSlotElement {}
export class HTMLSourceElement {}
export class HTMLSpanElement {}
export class HTMLStyleElement {}
export class HTMLTableCaptionElement {}
export class HTMLTableCellElement {}
export class HTMLTableColElement {}
export class HTMLTableElement {}
export class HTMLTableRowElement {}
export class HTMLTableSectionElement {}
export class HTMLTemplateElement {}
export class HTMLTextAreaElement {}
export class HTMLTimeElement {}
export class HTMLTitleElement {}
export class HTMLTrackElement {}
export class HTMLUListElement {}
export class HTMLUnknownElement {}
export class HTMLVideoElement {}
export class HashChangeEvent {}
export class History {}
export class InputEvent {}
export class KeyboardEvent {}
export class Location {}
export class MouseEvent {}
export class Navigator {}
export class PageTransitionEvent {}
export class Plugin {}
export class PluginArray {}
export class PointerEvent {}
export class PopStateEvent {}
export class PromiseRejectionEvent {}
export class RadioNodeList {}
export class Screen {}
export class Selection {}
export class SubmitEvent {}
export class TimeRanges {}
export class TrackEvent {}
export class UIEvent {}
export class ValidityState {}
export class VisualViewport {}
export class WheelEvent {}
export class Window {}
