export class SVGAElement {}
export class SVGAngle {}
export class SVGAnimateElement {}
export class SVGAnimateMotionElement {}
export class SVGAnimateTransformElement {}
export class SVGAnimatedAngle {}
export class SVGAnimatedBoolean {}
export class SVGAnimatedEnumeration {}
export class SVGAnimatedInteger {}
export class SVGAnimatedLength {}
export class SVGAnimatedLengthList {}
export class SVGAnimatedNumber {}
export class SVGAnimatedNumberList {}
export class SVGAnimatedPreserveAspectRatio {}
export class SVGAnimatedRect {}
export class SVGAnimatedString {}
export class SVGAnimatedTransformList {}
export class SVGAnimationElement {}
export class SVGCircleElement {}
export class SVGClipPathElement {}
export class SVGComponentTransferFunctionElement {}
export class SVGDefsElement {}
export class SVGDescElement {}
export class SVGElement {}
export class SVGEllipseElement {}
export class SVGFEBlendElement {}
export class SVGFEColorMatrixElement {}
export class SVGFEComponentTransferElement {}
export class SVGFECompositeElement {}
export class SVGFEConvolveMatrixElement {}
export class SVGFEDiffuseLightingElement {}
export class SVGFEDisplacementMapElement {}
export class SVGFEDistantLightElement {}
export class SVGFEDropShadowElement {}
export class SVGFEFloodElement {}
export class SVGFEFuncAElement {}
export class SVGFEFuncBElement {}
export class SVGFEFuncGElement {}
export class SVGFEFuncRElement {}
export class SVGFEGaussianBlurElement {}
export class SVGFEImageElement {}
export class SVGFEMergeElement {}
export class SVGFEMergeNodeElement {}
export class SVGFEMorphologyElement {}
export class SVGFEOffsetElement {}
export class SVGFEPointLightElement {}
export class SVGFESpecularLightingElement {}
export class SVGFESpotLightElement {}
export class SVGFETileElement {}
export class SVGFETurbulenceElement {}
export class SVGFilterElement {}
export class SVGForeignObjectElement {}
export class SVGGElement {}
export class SVGGeometryElement {}
export class SVGGradientElement {}
export class SVGGraphicsElement {}
export class SVGImageElement {}
export class SVGLength {}
export class SVGLengthList {}
export class SVGLineElement {}
export class SVGLinearGradientElement {}
export class SVGMPathElement {}
export class SVGMarkerElement {}
export class SVGMaskElement {}
export class SVGMatrix {}
export class SVGMetadataElement {}
export class SVGNumber {}
export class SVGNumberList {}
export class SVGPathElement {}
export class SVGPatternElement {}
export class SVGPoint {}
export class SVGPointList {}
export class SVGPolygonElement {}
export class SVGPolylineElement {}
export class SVGPreserveAspectRatio {}
export class SVGRadialGradientElement {}
export class SVGRect {}
export class SVGRectElement {}
export class SVGSVGElement {}
export class SVGScriptElement {}
export class SVGSetElement {}
export class SVGStopElement {}
export class SVGStringList {}
export class SVGStyleElement {}
export class SVGSwitchElement {}
export class SVGSymbolElement {}
export class SVGTSpanElement {}
export class SVGTextContentElement {}
export class SVGTextElement {}
export class SVGTextPathElement {}
export class SVGTextPositioningElement {}
export class SVGTitleElement {}
export class SVGTransform {}
export class SVGTransformList {}
export class SVGUnitTypes {}
export class SVGUseElement {}
export class SVGViewElement {}
