export class AbstractRange {}
export class Attr {}
export class CDATASection {}
export class CharacterData {}
export class Comment {}
export class CustomEvent {}
export class DOMException {}
export class DOMImplementation {}
export class DOMMatrix {}
export class DOMMatrixReadOnly {}
export class DOMParser {}
export class DOMPoint {}
export class DOMPointReadOnly {}
export class DOMQuad {}
export class DOMRect {}
export class DOMRectList {}
export class DOMRectReadOnly {}
export class DOMRequest {}
export class DOMStringList {}
export class DOMStringMap {}
export class DOMTokenList {}
export class Document {}
export class DocumentFragment {}
export class DocumentType {}
export class Element {}
export class Event {}
export class EventTarget {}
export class FormData {}
export class FormDataEvent {}
export class HTMLCollection {}
export class MutationEvent {}
export class MutationObserver {}
export class MutationRecord {}
export class NamedNodeMap {}
export class Node {}
export class NodeFilter {}
export class NodeIterator {}
export class NodeList {}
export class ProcessingInstruction {}
export class Range {}
export class StaticRange {}
export class Text {}
export class TreeWalker {}
