export class AbstractRange {}
export class Attr {}
export class CDATASection {}
export class CharacterData {}
export class Comment {}
export class CustomEvent {}
export class DOMException {}
export class DOMImplementation {}
export class DOMMatrix {}
export class DOMMatrixReadOnly {}
export class DOMParser {}
export class DOMPoint {}
export class DOMPointReadOnly {}
export class DOMQuad {}
export class DOMRect {}
export class DOMRectList {}
export class DOMRectReadOnly {}
export class DOMRequest {}
export class DOMStringList {}
export class DOMStringMap {}
export class DOMTokenList {}
export class Document {}
export class DocumentFragment {}
export class DocumentType {}
export class Element {}
export class Event {}
export class EventTarget {}
export class FormData {}
export class FormDataEvent {}
export class HTMLCollection {}
export class MutationEvent {}
export class MutationObserver {}
export class MutationRecord {}
export class NamedNodeMap {}
export class Node {}
export class NodeFilter {}
export class NodeIterator {}
export class NodeList {}
export class ProcessingInstruction {}
export class Range {}
export class StaticRange {}
export class Text {}
export class TreeWalker {}
export class BeforeUnloadEvent {}
export class CompositionEvent {}
export class ErrorEvent {}
export class FocusEvent {}
export class HTMLAllCollection {}
export class HTMLAnchorElement {}
export class HTMLAreaElement {}
export class HTMLAudioElement {}
export class HTMLBRElement {}
export class HTMLBaseElement {}
export class HTMLBodyElement {}
export class HTMLButtonElement {}
export class HTMLCanvasElement {}
export class HTMLDListElement {}
export class HTMLDataElement {}
export class HTMLDataListElement {}
export class HTMLDetailsElement {}
export class HTMLDialogElement {}
export class HTMLDirectoryElement {}
export class HTMLDivElement {}
export class HTMLDocument {}
export class HTMLElement {}
export class HTMLEmbedElement {}
export class HTMLFieldSetElement {}
export class HTMLFontElement {}
export class HTMLFormControlsCollection {}
export class HTMLFormElement {}
export class HTMLFrameElement {}
export class HTMLFrameSetElement {}
export class HTMLHRElement {}
export class HTMLHeadElement {}
export class HTMLHeadingElement {}
export class HTMLHtmlElement {}
export class HTMLIFrameElement {}
export class HTMLImageElement {}
export class HTMLInputElement {}
export class HTMLLIElement {}
export class HTMLLabelElement {}
export class HTMLLegendElement {}
export class HTMLLinkElement {}
export class HTMLMapElement {}
export class HTMLMarqueeElement {}
export class HTMLMediaElement {}
export class HTMLMenuElement {}
export class HTMLMetaElement {}
export class HTMLMeterElement {}
export class HTMLModElement {}
export class HTMLOListElement {}
export class HTMLObjectElement {}
export class HTMLOptGroupElement {}
export class HTMLOptionElement {}
export class HTMLOptionsCollection {}
export class HTMLOutputElement {}
export class HTMLParagraphElement {}
export class HTMLParamElement {}
export class HTMLPictureElement {}
export class HTMLPreElement {}
export class HTMLProgressElement {}
export class HTMLQuoteElement {}
export class HTMLScriptElement {}
export class HTMLSelectElement {}
export class HTMLSlotElement {}
export class HTMLSourceElement {}
export class HTMLSpanElement {}
export class HTMLStyleElement {}
export class HTMLTableCaptionElement {}
export class HTMLTableCellElement {}
export class HTMLTableColElement {}
export class HTMLTableElement {}
export class HTMLTableRowElement {}
export class HTMLTableSectionElement {}
export class HTMLTemplateElement {}
export class HTMLTextAreaElement {}
export class HTMLTimeElement {}
export class HTMLTitleElement {}
export class HTMLTrackElement {}
export class HTMLUListElement {}
export class HTMLUnknownElement {}
export class HTMLVideoElement {}
export class HashChangeEvent {}
export class History {}
export class InputEvent {}
export class KeyboardEvent {}
export class Location {}
export class MouseEvent {}
export class Navigator {}
export class PageTransitionEvent {}
export class Plugin {}
export class PluginArray {}
export class PointerEvent {}
export class PopStateEvent {}
export class PromiseRejectionEvent {}
export class RadioNodeList {}
export class Screen {}
export class Selection {}
export class SubmitEvent {}
export class TimeRanges {}
export class TrackEvent {}
export class UIEvent {}
export class ValidityState {}
export class VisualViewport {}
export class WheelEvent {}
export class Window {}
export class SVGAElement {}
export class SVGAngle {}
export class SVGAnimateElement {}
export class SVGAnimateMotionElement {}
export class SVGAnimateTransformElement {}
export class SVGAnimatedAngle {}
export class SVGAnimatedBoolean {}
export class SVGAnimatedEnumeration {}
export class SVGAnimatedInteger {}
export class SVGAnimatedLength {}
export class SVGAnimatedLengthList {}
export class SVGAnimatedNumber {}
export class SVGAnimatedNumberList {}
export class SVGAnimatedPreserveAspectRatio {}
export class SVGAnimatedRect {}
export class SVGAnimatedString {}
export class SVGAnimatedTransformList {}
export class SVGAnimationElement {}
export class SVGCircleElement {}
export class SVGClipPathElement {}
export class SVGComponentTransferFunctionElement {}
export class SVGDefsElement {}
export class SVGDescElement {}
export class SVGElement {}
export class SVGEllipseElement {}
export class SVGFEBlendElement {}
export class SVGFEColorMatrixElement {}
export class SVGFEComponentTransferElement {}
export class SVGFECompositeElement {}
export class SVGFEConvolveMatrixElement {}
export class SVGFEDiffuseLightingElement {}
export class SVGFEDisplacementMapElement {}
export class SVGFEDistantLightElement {}
export class SVGFEDropShadowElement {}
export class SVGFEFloodElement {}
export class SVGFEFuncAElement {}
export class SVGFEFuncBElement {}
export class SVGFEFuncGElement {}
export class SVGFEFuncRElement {}
export class SVGFEGaussianBlurElement {}
export class SVGFEImageElement {}
export class SVGFEMergeElement {}
export class SVGFEMergeNodeElement {}
export class SVGFEMorphologyElement {}
export class SVGFEOffsetElement {}
export class SVGFEPointLightElement {}
export class SVGFESpecularLightingElement {}
export class SVGFESpotLightElement {}
export class SVGFETileElement {}
export class SVGFETurbulenceElement {}
export class SVGFilterElement {}
export class SVGForeignObjectElement {}
export class SVGGElement {}
export class SVGGeometryElement {}
export class SVGGradientElement {}
export class SVGGraphicsElement {}
export class SVGImageElement {}
export class SVGLength {}
export class SVGLengthList {}
export class SVGLineElement {}
export class SVGLinearGradientElement {}
export class SVGMPathElement {}
export class SVGMarkerElement {}
export class SVGMaskElement {}
export class SVGMatrix {}
export class SVGMetadataElement {}
export class SVGNumber {}
export class SVGNumberList {}
export class SVGPathElement {}
export class SVGPatternElement {}
export class SVGPoint {}
export class SVGPointList {}
export class SVGPolygonElement {}
export class SVGPolylineElement {}
export class SVGPreserveAspectRatio {}
export class SVGRadialGradientElement {}
export class SVGRect {}
export class SVGRectElement {}
export class SVGSVGElement {}
export class SVGScriptElement {}
export class SVGSetElement {}
export class SVGStopElement {}
export class SVGStringList {}
export class SVGStyleElement {}
export class SVGSwitchElement {}
export class SVGSymbolElement {}
export class SVGTSpanElement {}
export class SVGTextContentElement {}
export class SVGTextElement {}
export class SVGTextPathElement {}
export class SVGTextPositioningElement {}
export class SVGTitleElement {}
export class SVGTransform {}
export class SVGTransformList {}
export class SVGUnitTypes {}
export class SVGUseElement {}
export class SVGViewElement {}
export class XMLDocument {}
export class XMLSerializer {}
export class XPathEvaluator {}
export class XPathExpression {}
export class XPathResult {}
export class XSLTProcessor {}
export class CaretPosition {}
export class CSS {}
export class CSS2Properties {}
export class CSSAnimation {}
export class CSSConditionRule {}
export class CSSCounterStyleRule {}
export class CSSFontFaceRule {}
export class CSSFontFeatureValuesRule {}
export class CSSGroupingRule {}
export class CSSImportRule {}
export class CSSKeyframeRule {}
export class CSSKeyframesRule {}
export class CSSLayerBlockRule {}
export class CSSLayerStatementRule {}
export class CSSMediaRule {}
export class CSSNamespaceRule {}
export class CSSPageRule {}
export class CSSRule {}
export class CSSRuleList {}
export class CSSStyleDeclaration {}
export class CSSStyleRule {}
export class CSSStyleSheet {}
export class CSSSupportsRule {}
export class CSSTransition {}
export class FontFace {}
export class FontFaceSet {}
export class FontFaceSetLoadEvent {}
export class FontFaceSource {}
export class MediaQueryList {}
export class MediaQueryListEvent {}
export class StyleSheet {}
export class StyleSheetList {}
