"use strict";
exports = {
  CanvasCaptureMediaStream,
  MediaCapabilities,
  MediaCapabilitiesInfo,
  MediaDeviceInfo,
  MediaDevices,
  MediaEncryptedEvent,
  MediaError,
  MediaKeyError,
  MediaKeyMessageEvent,
  MediaKeySession,
  MediaKeyStatusMap,
  MediaKeySystemAccess,
  MediaKeys,
  MediaList,
  MediaMetadata,
  MediaRecorder,
  MediaRecorderErrorEvent,
  MediaSession,
  MediaStream,
  MediaStreamEvent,
  MediaStreamTrack,
  MediaStreamTrackAudioSourceNode,
  MediaStreamTrackEvent,
};
