"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.document = globalThis.window.document;
exports.location = globalThis.window.location;
exports.history = globalThis.window.history;
exports.navigator = globalThis.window.navigator;
exports.window = globalThis.window;
exports.isBrowser = true;
exports.isServer = false;
exports.runtime = "browser";
