"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.window = undefined;
exports.document = undefined;
exports.location = undefined;
exports.history = undefined;
exports.navigator = undefined;
exports.isBrowser = false;
exports.isServer = true;
exports.runtime = "server";
