export declare const createImageBitmap: typeof window.createImageBitmap;
export declare const crypto: Crypto;
export declare const customElements: CustomElementRegistry;
export declare const devicePixelRatio: number;
export declare const document: Document;
export declare const fetch: typeof window.fetch;
export declare const history: History;
export declare const indexedDB: IDBFactory;
export declare const localStorage: Storage;
export declare const location: Location;
export declare const navigator: Navigator;
export declare const performance: Performance;
export declare const sessionStorage: Storage;
export declare const structuredClone: typeof window.structuredClone;
export declare const visualViewport: VisualViewport;
export declare const window: Window;
export declare const isBrowser: boolean;
export declare const isServer: boolean;
export declare const runtime: "browser" | "server";
