export class CaretPosition {}
export class CSS {}
export class CSS2Properties {}
export class CSSAnimation {}
export class CSSConditionRule {}
export class CSSCounterStyleRule {}
export class CSSFontFaceRule {}
export class CSSFontFeatureValuesRule {}
export class CSSGroupingRule {}
export class CSSImportRule {}
export class CSSKeyframeRule {}
export class CSSKeyframesRule {}
export class CSSLayerBlockRule {}
export class CSSLayerStatementRule {}
export class CSSMediaRule {}
export class CSSNamespaceRule {}
export class CSSPageRule {}
export class CSSRule {}
export class CSSRuleList {}
export class CSSStyleDeclaration {}
export class CSSStyleRule {}
export class CSSStyleSheet {}
export class CSSSupportsRule {}
export class CSSTransition {}
export class FontFace {}
export class FontFaceSet {}
export class FontFaceSetLoadEvent {}
export class FontFaceSource {}
export class MediaQueryList {}
export class MediaQueryListEvent {}
export class StyleSheet {}
export class StyleSheetList {}
